static_library("vm") {
  sources = [
    "chunk.cc",
    "chunk.h",
    "cow.cc",
    "cow.h",
    "value.cc",
    "value.h",
    "vm.cc",
    "vm.h",
  ]

  include_dirs = [ "//backend" ]
}

executable("kinglet") {
  sources = [
    "vm_main.cc",
  ]

  include_dirs = [ "//backend" ]

  deps = [ ":vm" ]
}

executable("cow_test") {
  sources = [
    "cow_test.cc",
  ]

  include_dirs = [ "//backend" ]

  deps = [ ":vm" ]
}
